String.toLocaleString({
	"en-US": {
		"%l_welcometotitanium": "Welcome to Titanium",
		"%l_tagline": "The only cross-platform mobile development framework with NATIVE UI and performance",
		"%l_agenda_title": "AGENDA",
		"%l_agenda1": "What is Titanium?",
		"%l_agenda2": "How does Titanium work?",
		"%l_agenda3": "What can Titanium do?",
		"%l_agenda4": "What's it like developing with Titanium?",
		"%l_agenda5": "How can I learn more?",
		"%l_whatis": "What is",
		"%l_important": "But more importantly...",
		"%l_why": "Why",
		"%l_dilemma": "The Dilemma:",
		"%l_somany": "So many native plaforms...",
		"%l_sofew": "so few RESOURCES",
		"%l_platform": "Platform",
		"%l_time_money_people":'TIME + MONEY + PEOPLE',
		"%l_scalability": "Scalability + Maintenance + Parity",
		"%l_theanswer": "Cross-platform development is the answer, but we don't want to...",
		"%l_suck": "Write once, SUCK everywhere",
		"%l_approach": "Common Approach",
		"%l_rendering": "Use a single rendering context, like",
		"%l_apihooks": "then add some native API hooks.",
		"%l_donetodeath": "see also, \"done to death\"",
		"%l_missing": "What are they all missing?",
		"%l_performance": "Performance",
		"%l_uicomponents": "UI Components",
		"%l_lookfeel": "Look & Feel",
		"%l_behavior": "Behavior",
		"%l_services": "Services",
		"%l_native": "NATIVE",
		"%l_titaniummobile": "Titanium Mobile is a platform for building best in class cross-platform mobile applications in JavaScript",
		"%l_nativeperf": "Only cross-platform mobile toolkit with native UI and performance",
		"%l_foss": "Free and open source under the Apache 2.0 license",
		"%l_supports": "Supports iOS, Android, Blackberry, and Mobile Web",
		"%l_howtitaniumworks": "How Titanium Works",
		"%l_youwritejavascript": "You write Javascript",
		"%l_titaniummaps": "Titanium maps your JS to native bindings",
		"%l_theformula": "Your JS + JS engine + native bindings = native mobile app",
		"%l_whatcanidowithit": "That's great, but what can I do with it?",
		"%l_topbrands": "Top brands",
		"%l_independent": "Independent success",
		"%l_numberone": "#1 apps",
		"%l_whatsthecodelike": "What's the code like?",
		"%l_workflow": "Development Workflow",
		"%l_workflow1": "UI and app logic coded in Javascript",
		"%l_workflow2": "Write code, manage projects, and package with Titanium Studio",
		"%l_workflow3": "Target multiple platforms from a single codebase",
		"%l_livecode": "Live Code Demo",
		"%l_learnmore": "Want to learn more?",
		"%l_learnmore1": "Github Code Samples",
		"%l_learnmore2": "Forging Titanium",
		"%l_learnmore3": "Video Training Series",
		"%l_learnmore4": "Wiki Documentation",
		"%l_learnmore5": "API Documentation",
		"%l_learnmore6": "Developer Blog",
		"%l_follow": "Follow",
		"%l_facebook": "Like us on Facebook",
		"%l_mailinglist": "Developer Mailing List",
		"%l_appcnews": "Appcelerator News",
		"%l_qa": "Q&A",
		"%l_thanks": "Thank You!"
	},
	"es": {
		"%l_welcometotitanium": "Bienvenido al Titanium",
		"%l_tagline": "La única cruz-plataforma móvil marco de desarrollo con la interfaz de usuario y el rendimiento de NATIVO",
		"%l_agenda_title": "ORDEN DEL DÍA",
		"%l_agenda1": "¿Qué es el Titanium?",
		"%l_agenda2": "¿Cómo Titanium de trabajo?",
		"%l_agenda3": "¿Qué se puede hacer Titanium?",
		"%l_agenda4": "¿Cómo es el desarrollo con el Titanium?",
		"%l_agenda5": "¿Cómo puedo aprender más?",
		"%l_whatis": "¿Qué es el",
		"%l_important": "Pero lo más importante...",
		"%l_why": "¿Por qué",
		"%l_dilemma": "El Dilema:",
		"%l_somany": "Plataformas nativas tantos...",
		"%l_sofew": "tan pocos RECURSOS",
		"%l_platform": "Plataforma",
		"%l_time_money_people":'TIEMPO + DINERO + PERSONAS',
		"%l_scalability": "Escalabilidad + Mantenimiento + Paridad",
		"%l_theanswer": "Multi-plataforma el desarrollo es la respuesta, pero no quiero",
		"%l_suck": "Escribir una vez, CHUPAR todo el mundo",
		"%l_approach": "Enfoque Común",
		"%l_rendering": "Use un contexto de representación, como",
		"%l_apihooks": "a continuación, añadir algunos nativos ganchos API.",
		"%l_donetodeath": "véase también, \"hecho a la muerte\"",
		"%l_missing": "¿Qué son todas las que faltan?",
		"%l_performance": "Rendimiento",
		"%l_uicomponents": "Componentes UI",
		"%l_lookfeel": "Look & Feel",
		"%l_behavior": "Comportamiento",
		"%l_services": "Servicios",
		"%l_native": "NATIVO",
		"%l_titaniummobile": "Titanio Mobile es una plataforma para la construcción de los mejores multiplataformas aplicaciones móviles en JavaScript",
		"%l_nativeperf": "Sólo la cruz-plataforma móvil con kit de herramientas de interfaz de usuario nativa y el rendimiento",
		"%l_foss": "Libre y de código abierto bajo licencia Apache 2.0",
		"%l_supports": "Compatible con iOS, Android, Blackberry, y Mobile Web",
		"%l_howtitaniumworks": "Cómo Funciona el Titanium",
		"%l_youwritejavascript": "Usted escribe Javascript",
		"%l_titaniummaps": "Mapas de Titanium de su JS a los enlaces de nativos",
		"%l_theformula": "Su JS + JS motor + enlaces nativos = aplicaciones móviles nativas",
		"%l_whatcanidowithit": "Eso está muy bien, ¿Qué puedo hacer con él?",
		"%l_topbrands": "Las mejores marcas",
		"%l_independent": "Exito independiente",
		"%l_numberone": "#1 aplicaciones",
		"%l_whatsthecodelike": "¿Cuál es el código como?",
		"%l_workflow": "Desarrollo de Flujo de Trabajo",
		"%l_workflow1": "IU y la lógica de la aplicación codificados en JavaScript",
		"%l_workflow2": "Escribir código, gestión de proyectos, y el paquete con el Titanium Studio",
		"%l_workflow3": "Objetivos múltiples plataformas desde un único código base",
		"%l_livecode": "Demostración en vivo del Código",
		"%l_learnmore": "¿Quieres saber más?",
		"%l_learnmore1": "Github Ejemplos de Código",
		"%l_learnmore2": "Forging Titanium",
		"%l_learnmore3": "Serie de Videos de Capacitación",
		"%l_learnmore4": "Wiki de Documentación",
		"%l_learnmore5": "API de Documentación",
		"%l_learnmore6": "Blog de los Programadores",
		"%l_follow": "Seguir",
		"%l_facebook": "Al igual que nosotros en Facebook",
		"%l_mailinglist": "Desarrollador la Lista de Correo",
		"%l_appcnews": "Appcelerator Noticias",
		"%l_qa": "Q&A",
		"%l_thanks": "¡Gracias!"
	}
});
