String.toLocaleString({
	"en-US": {
		"%l_welcometotitanium": "Welcome to Titanium",
		"%l_tagline": "The only cross-platform mobile development framework with NATIVE UI and performance",
		"%l_agenda_title": "AGENDA",
		"%l_agenda1": "What is Titanium?",
		"%l_agenda2": "How does Titanium work?",
		"%l_agenda3": "What can Titanium do?",
		"%l_agenda4": "What's it like developing with Titanium?",
		"%l_agenda5": "How can I learn more?",
		"%l_whatis": "What is",
		"%l_important": "But more importantly...",
		"%l_why": "Why",
		"%l_dilemma": "The Dilemma:",
		"%l_somany": "So many native plaforms...",
		"%l_sofew": "so few RESOURCES",
		"%l_platform": "Platform",
		"%l_time_money_people":'TIME + MONEY + PEOPLE',
		"%l_scalability": "Scalability + Maintenance + Parity",
		"%l_theanswer": "Cross-platform development is the answer, but we don't want to...",
		"%l_suck": "Write once, SUCK everywhere",
		"%l_approach": "Common Approach",
		"%l_rendering": "Use a single rendering context, like",
		"%l_apihooks": "then add some native API hooks.",
		"%l_donetodeath": "see also, \"done to death\"",
		"%l_missing": "What are they all missing?",
		"%l_performance": "Performance",
		"%l_uicomponents": "UI Components",
		"%l_lookfeel": "Look & Feel",
		"%l_behavior": "Behavior",
		"%l_services": "Services",
		"%l_native": "NATIVE",
		"%l_titaniummobile": "Titanium Mobile is a platform for building best in class cross-platform mobile applications in JavaScript",
		"%l_nativeperf": "Only cross-platform mobile toolkit with native UI and performance",
		"%l_foss": "Free and open source under the Apache 2.0 license",
		"%l_supports": "Supports iOS, Android, Blackberry, and Mobile Web",
		"%l_howtitaniumworks": "How Titanium Works",
		"%l_youwritejavascript": "You write Javascript",
		"%l_titaniummaps": "Titanium maps your JS to native bindings",
		"%l_theformula": "Your JS + JS engine + native bindings = native mobile app",
		"%l_whatcanidowithit": "That's great, but what can I do with it?",
		"%l_topbrands": "Top brands",
		"%l_independent": "Independent success",
		"%l_numberone": "#1 apps",
		"%l_whatsthecodelike": "What's the code like?",
		"%l_workflow": "Development Workflow",
		"%l_workflow1": "UI and app logic coded in Javascript",
		"%l_workflow2": "Write code, manage projects, and package with Titanium Studio",
		"%l_workflow3": "Target multiple platforms from a single codebase",
		"%l_livecode": "Live Code Demo",
		"%l_learnmore": "Want to learn more?",
		"%l_learnmore1": "Github Code Samples",
		"%l_learnmore2": "Forging Titanium",
		"%l_learnmore3": "Video Training Series",
		"%l_learnmore4": "Wiki Documentation",
		"%l_learnmore5": "API Documentation",
		"%l_learnmore6": "Developer Blog",
		"%l_follow": "Follow",
		"%l_facebook": "Like us on Facebook",
		"%l_mailinglist": "Developer Mailing List",
		"%l_appcnews": "Appcelerator News",
		"%l_qa": "Q&A",
		"%l_thanks": "Thank You!"
	},
	"es": {
		"%l_welcometotitanium": "Bienvenido a Titanium",
		"%l_tagline": "El único framework de apps móviles multi-plataforma con rendimiento NATIVO",
		"%l_agenda_title": "AGENDA",
		"%l_agenda1": "¿Qué es Titanium?",
		"%l_agenda2": "¿Cómo funciona?",
		"%l_agenda3": "¿Qué se puede hacer con Titanium?",
		"%l_agenda4": "¿Cómo se desarrolla?",
		"%l_agenda5": "¿Cómo puedo aprender más?",
		"%l_whatis": "¿Qué es ",
		"%l_important": "Pero lo más importante...",
		"%l_why": "¿Por qué",
		"%l_dilemma": "Dilema:",
		"%l_somany": "Muchas plataformas nativas...",
		"%l_sofew": "...y tan pocos RECURSOS",
		"%l_platform": "Plataforma",
		"%l_time_money_people":'TIEMPO + DINERO + PERSONAS',
		"%l_scalability": "Escalabilidad + Mantenimiento + Paridad",
		"%l_theanswer": "La respuesta es desarrollar en multi-plataforma, pero no queremos...",
		"%l_suck": "Write once, SUCK everywhere",
		"%l_approach": "Qué hacen otros",
		"%l_rendering": "Usar un contexto de representación único, como",
		"%l_apihooks": "y añadirle algún enlace a la API nativa.",
		"%l_donetodeath": "o lo que es lo mismo, \"solución mediocre\"",
		"%l_missing": "¿De qué se están olvidando?",
		"%l_performance": "Rendimiento",
		"%l_uicomponents": "Componentes UI",
		"%l_lookfeel": "Look & Feel",
		"%l_behavior": "Comportamiento",
		"%l_services": "Servicios",
		"%l_native": "NATIVO",
		"%l_titaniummobile": "Titanium Mobile permite desarrollar aplicaciones móvil multiplataforma en JavaScript",
		"%l_nativeperf": "El único kit de desarrollo de aplicaciones móviles con rendimiento y apariencia nativa.",
		"%l_foss": "Gratuíto y open source bajo licencia Apache 2.0",
		"%l_supports": "Compatible con iOS, Android, Blackberry y Mobile Web",
		"%l_howtitaniumworks": "Cómo Funciona Titanium",
		"%l_youwritejavascript": "Se programa en JavaScript",
		"%l_titaniummaps": "Titanium mapea las llamadas JavaScript a llamadas a la API nativa",
		"%l_theformula": "Código JS + motor JS + enlaces nativos = aplicaciones móviles nativas",
		"%l_whatcanidowithit": "Genial. Pero, ¿Qué puedo hacer con Titanium?",
		"%l_topbrands": "Las mejores marcas",
		"%l_independent": "Éxito en más de 30.000 apps",
		"%l_numberone": "Aplicaciones #1",
		"%l_whatsthecodelike": "¿Cómo se desarrolla?",
		"%l_workflow": "DEVELOPMENT WORKFLOW",
		"%l_workflow1": "UI y lógica de la aplicación en JavaScript",
		"%l_workflow2": "Código, gestión de proyectos, compilado y distribución con Titanium Studio",
		"%l_workflow3": "Trabaja para varias plataformas desde un único código base",
		"%l_livecode": "DEMO",
		"%l_learnmore": "¿Quieres saber más?",
		"%l_learnmore1": "Github Code Samples",
		"%l_learnmore2": "Forging Titanium",
		"%l_learnmore3": "Video Training Series",
		"%l_learnmore4": "Wiki Documentation",
		"%l_learnmore5": "API Documentation",
		"%l_learnmore6": "Developer Blog",
		"%l_follow": "Síguenos en",
		"%l_facebook": "Página en Facebook",
		"%l_mailinglist": "Lista de correo de programadores",
		"%l_appcnews": "Noticias Appcelerator",
		"%l_qa": "Q&A",
		"%l_thanks": "¡Gracias!"
	}
});
